# Generated by Django 3.2.4 on 2021-06-28 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lev', models.CharField(blank=True, max_length=20, null=True)),
                ('plot', models.CharField(blank=True, max_length=2000, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='Locations/')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last', models.CharField(blank=True, max_length=20, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='Race/')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('creator', models.CharField(blank=True, max_length=20, null=True)),
                ('release', models.IntegerField(default=0)),
                ('plot', models.FileField(blank=True, null=True, upload_to='plot/')),
                ('img', models.ImageField(blank=True, null=True, upload_to='Game/')),
                ('classes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DragonAge.classes')),
                ('locations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DragonAge.locations')),
                ('race', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DragonAge.race')),
            ],
        ),
    ]
