# Generated by Django 3.2.4 on 2021-06-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DragonAge', '0002_auto_20210628_0408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='classes',
        ),
        migrations.AddField(
            model_name='game',
            name='classes',
            field=models.ManyToManyField(to='DragonAge.Classes'),
        ),
        migrations.RemoveField(
            model_name='game',
            name='companion',
        ),
        migrations.AddField(
            model_name='game',
            name='companion',
            field=models.ManyToManyField(to='DragonAge.Companion'),
        ),
        migrations.RemoveField(
            model_name='game',
            name='locations',
        ),
        migrations.AddField(
            model_name='game',
            name='locations',
            field=models.ManyToManyField(to='DragonAge.Locations'),
        ),
        migrations.RemoveField(
            model_name='game',
            name='race',
        ),
        migrations.AddField(
            model_name='game',
            name='race',
            field=models.ManyToManyField(to='DragonAge.Race'),
        ),
    ]
