# Generated by Django 3.2.4 on 2021-06-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DragonAge', '0004_auto_20210628_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='plot',
            field=models.CharField(blank=True, max_length=30000, null=True),
        ),
    ]
