# Generated by Django 3.2.4 on 2021-09-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DragonAge', '0005_alter_game_plot'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='plot',
            field=models.CharField(blank=True, max_length=30000, null=True),
        ),
    ]
