# Generated by Django 3.2.4 on 2021-09-20 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DragonAge', '0007_companion_plot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companion',
            options={'ordering': ['imy']},
        ),
    ]
