# Generated by Django 3.2.4 on 2021-09-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DragonAge', '0008_alter_companion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='plot',
            field=models.CharField(blank=True, max_length=30000, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
