# Generated by Django 3.2.4 on 2021-09-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DragonAge', '0009_auto_20210920_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='class/'),
        ),
    ]
