# Generated by Django 3.2.4 on 2021-09-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DragonAge', '0012_alter_game_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companion',
            name='game',
        ),
        migrations.AddField(
            model_name='companion',
            name='game',
            field=models.ManyToManyField(to='DragonAge.Game'),
        ),
    ]
