# Generated by Django 3.2.4 on 2021-09-20 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DragonAge', '0014_auto_20210921_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companion',
            name='game',
        ),
        migrations.AddField(
            model_name='companion',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DragonAge.game'),
        ),
    ]
